(function(p){"use strict";var a={exports:{}},s={};/**
 * @license React
 * react-jsx-runtime.production.min.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */var x=p,f=Symbol.for("react.element"),h=Symbol.for("react.fragment"),g=Object.prototype.hasOwnProperty,m=x.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner,y={key:!0,ref:!0,__self:!0,__source:!0};function l(o,r,i){var e,t={},c=null,u=null;i!==void 0&&(c=""+i),r.key!==void 0&&(c=""+r.key),r.ref!==void 0&&(u=r.ref);for(e in r)g.call(r,e)&&!y.hasOwnProperty(e)&&(t[e]=r[e]);if(o&&o.defaultProps)for(e in r=o.defaultProps,r)t[e]===void 0&&(t[e]=r[e]);return{$$typeof:f,type:o,key:c,ref:u,props:t,_owner:m.current}}s.Fragment=h,s.jsx=l,s.jsxs=l,a.exports=s;var n=a.exports;const d=window.React;class b extends d.Component{constructor(r){super(r),this.state={hasError:!1,error:null}}static getDerivedStateFromError(r){return{hasError:!0,error:r}}componentDidCatch(r,i){console.error("[Finance Plugin] Error caught:",r,i)}render(){var r;return this.state.hasError?n.jsxs("div",{style:{padding:"20px",color:"red",background:"#fee2e2",borderRadius:"5px",margin:"20px"},children:[n.jsx("h3",{children:"Finance Plugin Error"}),n.jsx("p",{children:"Something went wrong in the Finance module."}),n.jsx("pre",{style:{fontSize:"0.8em"},children:(r=this.state.error)==null?void 0:r.toString()})]}):this.props.children}}const R=({api:o,onClose:r})=>{const i=e=>{const t=e.target;console.log("[Finance Tracker] Action:",e.type,"on",t.tagName,t.innerText||t.className)};return n.jsx(b,{children:n.jsxs("div",{onClickCapture:i,style:{padding:"20px",height:"100%",background:"#fff",display:"flex",flexDirection:"column"},children:[n.jsxs("div",{style:{display:"flex",justifyContent:"space-between",alignItems:"center"},children:[n.jsx("h1",{style:{color:"#064e3b"},children:"Finance (Plugin)"}),n.jsx("button",{onClick:r,style:{background:"#e2e8f0",border:"none",padding:"10px 20px",borderRadius:"5px",cursor:"pointer"},children:"Close Plugin"})]}),n.jsxs("div",{style:{marginTop:"20px",display:"flex",gap:"10px"},children:[n.jsx("button",{style:{padding:"10px",background:"#059669",color:"#fff",border:"none",borderRadius:"4px",cursor:"pointer"},children:"View Reports"}),n.jsx("button",{style:{padding:"10px",background:"#10b981",color:"#fff",border:"none",borderRadius:"4px",cursor:"pointer"},children:"Process Payroll"}),n.jsx("button",{style:{padding:"10px",background:"#ef4444",color:"#fff",border:"none",borderRadius:"4px",cursor:"pointer"},onClick:()=>{throw new Error("Simulated crash!")},children:"Simulate Crash"})]}),n.jsx("p",{style:{marginTop:"20px"},children:"This module is now robust with error boundaries and tracks user actions."})]})})};window.RitaPlugin={mount:(o,r)=>{const e=window.ReactDOM.createRoot(o);e.render(d.createElement(R,r)),window.RitaPlugin._root=e},unmount:()=>{const o=window.RitaPlugin._root;o&&o.unmount()}}})(React);
